name: PR Validation

on:
  pull_request:
    branches:
      - 'main'
      - 'develop'

jobs:
  UnitTest:
    runs-on: macos-12
    env:
      DEVELOPER_DIR: /Applications/Xcode_14.0.1.app/Contents/Developer
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - uses: webfactory/ssh-agent@v0.4.1
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Run code to resolve SSH host issue for Xcode
        run: for ip in $(dig @8.8.8.8 github.com +short); do ssh-keyscan github.com,$ip; ssh-keyscan $ip; done 2>/dev/null >> ~/.ssh/known_hosts

      - name: Test
        run: |
          make test
          xcrun llvm-cov export \
            -format=lcov \
            -instr-profile \
            build/Build/ProfileData/**/Coverage.profdata \
            build/Build/Products/**/Smoothie.app/Smoothie > build/lcov.info
      - name: Log Coverage
        uses: kishikawakatsumi/xcresulttool@v1
        with:
          title: Test Coverage
          show-passed-tests: false
          token: ${{ secrets.GITHUB_TOKEN }}
          path: ./build/test-results.xcresult
        if: success() || failure()
